# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
steps:

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '6.x'

- task: NuGetToolInstaller@1
  inputs:
    versionSpec: 
    checkLatest: true

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(Build.SourcesDirectory)\\TraineeProject.Data\\TraineeProject.Data.sqlproj'
    clean: true

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: true
    arguments: '--configuration $(buildConfiguration) --output $(System.DefaultWorkingDirectory)/web_app'

- task: SqlAzureDacpacDeployment@1
  inputs:
    azureSubscription: 'Visual Studio Enterprise Subscription(03706ad7-97e6-4ed3-ab37-a17ec2d4dad8)'
    AuthenticationType: 'server'
    ServerName: 'cdbtrainee.database.windows.net'
    DatabaseName: 'traineedb-Logs'
    SqlUsername: 'calumdb'
    SqlPassword: $(SQLPASS)
    deployType: 'DacpacTask'
    DeploymentAction: 'Publish'
    DacpacFile: '$(System.DefaultWorkingDirectory)/database/*.dacpac'
    IpDetectionMethod: 'AutoDetect'

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Visual Studio Enterprise Subscription(03706ad7-97e6-4ed3-ab37-a17ec2d4dad8)'
    appType: 'webApp'
    WebAppName: 'calumdbtraineeproject'
    packageForLinux: '$(System.DefaultWorkingDirectory)/web_app/*.zip'
    enableCustomDeployment: true
    DeploymentType: 'webDeploy'
    RemoveAdditionalFilesFlag: true