trigger:
  branches:
    include:
        - main
  paths:
    include:
        - TraineProject.FunctionApp/**
        - build-deploy-function.yml


pool:
  vmImage: 'windows-latest'

variables:
  - name: "solution" 
    value: 'TraineProject.FunctionApp/*.sln'
  - name: "buildPlatform"
    value: 'Any CPU'
  - name: "buildConfiguration"
    value: 'Release'
  # Azure Resource Manager connection created during pipeline creation
  - name: "azureSubscription"
    value: '89792dac-8f91-4b45-8ecf-0d367cc71c92'

  # Function app name
  - name: "functionAppName" 
    value: 'calumdbtraineeprojectfunction'

  # Agent VM image name
  - name: "vmImageName"
    value: 'windows-2019'

  - group: Pipeline-Variables
steps:

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '6.x'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'TraineProject.FunctionApp/**/*.csproj'
    arguments: '--output $(System.DefaultWorkingDirectory)/function_app/'
    
- task: FileTransform@1
  inputs:
    folderPath: '$(System.DefaultWorkingDirectory)/function_app/'
    fileType: 'json'
    targetFiles: '**/host.json'

- task: AzureFunctionApp@1
  displayName: 'Azure functions app deploy'
  inputs:
    azureSubscription: '$(azureSubscription)'
    appType: functionApp
    appName: $(functionAppName)
    package: '$(System.DefaultWorkingDirectory)/function_app/'